Catch errors from EclipseHelper annotation indexing
EclipseHelper would create an index that had non-existent class
prefixes. Thus, if you tried to instantiate them you received a
NoClassDefFoundError that was uncaught.